name: Data Processing CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-processing:latest --push .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy data-processing --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-processing:latest --region ${{ secrets.GCP_REGION }} --platform managed --allow-unauthenticated

